DROP TABLE IF EXISTS Investor CASCADE;

DROP TABLE IF EXISTS Car CASCADE;

DROP TABLE IF EXISTS Client CASCADE;

DROP TABLE IF EXISTS "Order" CASCADE;

DROP TABLE IF EXISTS InvestorBenefit CASCADE;

DROP TABLE IF EXISTS Bebtors CASCADE;

